---
- name: install httpd and apache2
  hosts: all
  become: true

  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest
      when: ansible_os_family == "RedHat"
      tags:
        - install-httpd
    
    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"
      tags:
        - start-httpd

    - name: install apache2
      apt:
        name: apache2
        state: latest
      when: ansible_os_family == "Debian"
      tags: 
        - install-apache2

    - name: start apache2
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"
      tags:
        - start-apache2






