---
- name: nginx install and start services
  hosts: all
  become: true

  tasks:
    - name: loop through list
      yum:
        name: epel-release
        update_cache: yes
        state: latest
      when: ansible_distribution == 'centos'
      tags:
        - install-epel

    - name: install nginx
      package:
        name: nginx
        state: latest

    - name: start nginx
      service:
        name: nginx
        state: started
      tags:
        - start-nginx

    - name: stop nginx
      service:
        name: nginx
        state: stopped
      tags:
        - stop-nginx

