---
- name: install tomcat server
  hosts: all
  become: true

  vars:
    - tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.78/bin/apache-tomcat-9.0.78.tar.gz
    - tomcat_package: apache-tomcat-9.0.78

  tasks:
    - name: install java
      yum:
        name: java
        state: latest

    - name: download tomcat package
      get_url:
        url: "{{ tomcat_url }}"
        dest: /usr/local

    - name: extract tomcat package
      unarchive:
        src: /usr/local/{{tomcat_package}}.tar.gz
        dest: /usr/local
        remote_src: yes
    
    - name: start tomcat services
      shell: /usr/local/tomcat/bin/startup.sh
      tags:
        - start-tomcat

    - name: stop tomcat services
      shell: /usr/local/tomcat/bin/shutdown.sh
      tags:
        - stop-tomcat

